---
# tasks file for install_jre_and_jenkins

- name: Add an apt signing key for Jenkins
  apt_key:
    url: "{{ jenkins_signing_key_url }}"
    state: present

- name: Add Jenkins apt repo
  apt_repository:
    repo: "{{ jenkins_apt_repo }}"
    state: present
    filename: jenkins
    update_cache: yes


- name: Install JRE 
  apt:
    name: openjdk-11-jre
    state: present 

- name: Install Jenkins 
  apt:
    name: jenkins
    state: present 